In [6]:
import numpy as np


[1 2 3 4 5]
1


In [7]:
#Exercici 1
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.ndim)

[1 2 3 4 5]
1


In [16]:
#Exercici 2
array2 = np.random.randint(100, size=(5, 5))
print(array2)


[[ 1 63 15 45 60]
 [62 91 41 15 20]
 [48 81 52 85 69]
 [74  1 98 59  0]
 [15 76 46  0  2]]


In [30]:
#Exercici 3
array3 = np.random.randint(20, size=(4, 3))
print(array3)

[[12  0 19]
 [17 17 18]
 [ 7 11 12]
 [19 13 13]]


In [29]:
array3.sum(axis=1)

array([22, 29,  7, 21])

In [31]:
array3.sum(axis=0)

array([55, 41, 62])

In [35]:
#Exercici 4
import numpy as np

np.random.seed(10)
var1 = np.random.randint(0, 5, 8)
var2 = var1 + np.random.normal(0, 5, 8)
np.corrcoef(var1, var2)

array([[1.        , 0.41749225],
       [0.41749225, 1.        ]])